[package]
name = "virtual-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colog = "1.2.0"
env_logger = "0.10.0"
log = "0.4.17"
